# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f23bd6fa4273a5bf3824852017c273af073778215c1e88e182804ebcafc66962b37f4a1524753dacd80af0956ae7c16d0bee02505f0f0743f8f7eb2322865fc0

test:
  secret_key_base: 118bf3d56ea17560514a7eaf3de5bc5f03c4ae49593037b2b92e4fad30efe3b6e71257f589bfb926b193ea1a0613bf522ec70c5e4aa5be96a200b9e5d29a86d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
